from .vars import ENV_VARS


class DERIVED_VARS:
    IS_DEVELOPMENT = ENV_VARS.FLASK_ENV == 'development'
    PG_URL = f'postgres://{ENV_VARS.DATABASE_USER}:{ENV_VARS.DATABASE_PASSWORD}@{ENV_VARS.DATABASE_HOST}/{ENV_VARS.DATABASE_DBNAME}'
    PROXY_LIST = ENV_VARS.PROXIES.split(",")
